# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Hieu Vu
title: Fresher Reactjs Developer
email: xoaixanh.muoii95@gmail.com
website: www.github.com/suskull

# Social links
twitter_username: 
github_username:  suskull
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: 
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hieu and I'm a software developer.I have worked at a company named TMA-Solutions in HCM about python and machine learing. But now i'm learning React js and so far are react native. I like to become a BrSE in future.

  I have skills in: <mark>Reactjs </mark> and <mark>HTML, SCSS, Boostrap</mark> and basic knowledge in backend <mark>MongooseDB, Firebase, Nodejs</mark> and aslo basic knowledge about <mark>Authiencation security</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Language
more_content: | # this will include new lines to allow paragraphs
  I can speak 3 languages
   - Vietnamese - Mother tounge
   - English - Ielts 5.5
   - Japanese - N4
   
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Gaming
   - Fooball
   - Comic


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
